feat: LOGO_DESTINATION env var added for use it on Header component
edx/frontend-app-gradebook pull request #186
Opened 2021-05-25 21:42 UTC by ChrisChV

On index.js file of the Header component, currently there is a hard-coded link of `https://www.edx.org`. I added a new environment variable LOGO_DESTINATION to use it in this Header.
I have also added a mechanism to use the LMS_BASE_URL environment variable if the LOGO_DESTINATION environment variable is not found or is null.

Issue: https://github.com/openedx/build-test-release-wg/issues/55

**What changed?**

- This creates new environment variable LOGO_DESTINATION, sets the `.env.development` default to `http://localhost:18000` and the `.env` default to null.
- This updates the index.jsx file in the Header component to use the env var LOGO_DESTINATION.

**Developer Checklist**
- [X] Test suites passing
- [ ] Documentation and test plan updated, if applicable
- [ ] Received code-owner approving review
- [ ] Bumped version number [package.json](../package.json)

**Testing Instructions**

If you start your local development server for gradebook and you load a course, when you click in the header logo, then it should redirect to the LMS dashboard.

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ]  I've done a visual code review
- [ ] I've tested the new functionality

FYI: @edx/masters-devs-gta

2021-05-25 21:42 UTC, edx-webhook commented
Thanks for the pull request, @ChrisChV! I've created [OSPR-5806](https://openedx.atlassian.net/browse/OSPR-5806) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-05-26 13:09 UTC, sarina commented
@davidjoy didn't you fix this already?

2021-05-26 14:03 UTC, natabene commented
@ChrisChV Thank you for the contribution! Once you have signed our Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

2021-05-26 17:49 UTC, essiocolom commented
@natabene we already signed the Entity Contributor Agreement and sent it to legal as we are going to be contributing as Bitmaker and @ChrisChV is part of the organization 👍  By the way, we are still waiting for them to confirm everything is okay

2021-05-26 17:53 UTC, natabene commented
@ChrisChV Thank you for an update! They will process and get back to you soon.

2021-05-26 21:39 UTC, ChrisChV commented
Hi @natabene.  We have already been authorized as a bitmaker to contribute

2021-05-27 01:37 UTC, davidjoy commented
Looking around at the shared MFE header, I think we should set the logo destination to point at the dashboard for consistency:

`${config.LMS_BASE_URL}/dashboard`

In which case we don't need to add a new environment variable specific to gradebook. 

See shared header implementation here: https://github.com/edx/frontend-component-header/blob/3726792df260e72bcf9be6cd3bc921b880255604/src/Header.jsx#L82

2021-05-27 01:51 UTC, ChrisChV commented
> Looking around at the shared MFE header, I think we should set the logo destination to point at the dashboard for consistency:
> 
> `${config.LMS_BASE_URL}/dashboard`
> 
> In which case we don't need to add a new environment variable specific to gradebook.
> 
> See shared header implementation here: https://github.com/edx/frontend-component-header/blob/3726792df260e72bcf9be6cd3bc921b880255604/src/Header.jsx#L82

@davidjoy In this case it is better to place the logo destination value in the Header as I have done now? Or pass that value through the Header props from the index file, as being done in the link you shared?

2021-05-27 16:07 UTC, natabene commented
@ChrisChV Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward. @davidjoy Would you like to review?

2021-05-27 20:11 UTC, natabene commented
@mattcarter FYI this PR coming.

2021-05-28 01:18 UTC, ChrisChV commented
@davidjoy Please review the new changes, I added a new logic to solve this using what you commented and without creating a new env var

2021-05-28 15:33 UTC, natabene commented
@mattcarter Do you want to have a look now?

2021-05-28 15:48 UTC, jansenk commented
@mattcarter @natabene I've got some spare cycles, I can review this if you'd like

2021-05-28 16:51 UTC, mattcarter commented
@jansenk, that would be great.  Please review and engage with @davidjoy

2021-06-01 13:13 UTC, jansenk approved these changes
Looks good! Small style suggestion

2021-06-03 14:16 UTC, davidjoy requested changes
I think we can simplify this and just put the URL in the hyperlink.  The index.jsx file doesn't really need to know about the URL/this code isn't reused with different URLs.

2021-06-03 14:16 UTC, davidjoy commented on src/components/Header/index.jsx
> +          <Hyperlink {...logoProps}>
I think this line should just read:

```
<Hyperlink destination={`${getConfig().LMS_BASE_URL}/dashboard`}>
```

It's not really a configurable thing/there doesn't seem to be much value in passing it down from above.

2021-06-05 00:27 UTC, ChrisChV commented
@davidjoy It's done

2021-06-11 19:21 UTC, davidjoy approved these changes

2021-06-14 16:21 UTC, natabene commented
@davidjoy @jansenk If this is good to merge, let's merge.

2021-06-14 17:51 UTC, merged

2021-06-14 17:51 UTC, edx-webhook commented
@ChrisChV 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-gradebook&entry.867055334=https://github.com/edx/frontend-app-gradebook/pull/186&entry.1484655318=https://github.com/ChrisChV&entry.752974735=2021-05-25+21:42&entry.1917517419=2021-06-14+17:51&entry.2133058324=Yes) so we can improve your experience in the future.